### ISSUE TITLE
[BUG] Could not resolve dependencies

### ISSUE THREAD

**Issue by Justman100** [Geik-xyz/Farmer-v6#40]
Have tried to build the plugin! But, only this comes:

> Could not resolve dependencies for project xyz.geik.farmer:Farmer:jar:v6-b005: The following artifacts could not be resolved: bukkit.org:craftbukkit:jar:1.7.9, spigotmc.org:spigot-1.9.2:jar:1.9.2, spigotmc.org:spigot-1.9.4:jar:1.9.4, spigotmc.org:spigot-1.12:jar:1.12, spigotmc.org:spigot-1.10:jar:1.10, spigotmc.org:spigot-1.11:jar:1.11, spigotmc.org:spigot-1.9:jar:1.9, spigotmc.org:spigot-1.8:jar:1.8, spigotmc.org:spigot.1.8.3:jar:1.8.3, spigotmc.org:spigot.1.8.4:jar:1.8.4, spigotmc.org:spigot.1.8.6:jar:1.8.6, spigotmc.org:spigot.1.8.8:jar:1.8.8, spigotmc.org:spigot-1649:jar:1.7.10: Could not find artifact bukkit.org:craftbukkit:jar:1.7.9 at specified path /root/.m2/repository/com/wasteofplastic/askyblock/3.0.9.4/lib/craftbukkit-1.7.9-R0.3-20140705.002733-4.jar

**Comment by poyrazinan** [comment]
Can you try develop branch

**Comment by Justman100** [comment]
> Can you try to compile develop branch

Have tried with both branches

**Comment by poyrazinan** [comment]
> > Can you try to compile develop branch
> 
> Have tried with both branches

How you try to compile the plugin

**Comment by Justman100** [comment]
> > > Can you try to compile develop branch
> > 
> > 
> > Have tried with both branches
> 
> How you try to compile the plugin

With the main branch

```
git init
git pull https://github.com/Geik-xyz/Farmer-v6.git
mvn package
```
<br>

With the develope branch

```
git init
git remote add origin https://github.com/Geik-xyz/Farmer-v6.git
git pull origin develope
mvn package
```

**Comment by poyrazinan** [comment]
Can you try to use commands below.
One of them should fix your issue.

1. mvn compile
2. mvn test-compile
3. maven install

> mvn package tries to package everything together. But you should download dependencies first to use this command. One of the 3 command should download the requirements of project.

**Comment by Justman100** [comment]
> Can you try to use commands below. One of them should fix your issue.
> 
>     1. mvn compile
> 
>     2. mvn test-compile
> 
>     3. maven install
> 
> 
> > mvn package tries to package everything together. But you should download dependencies first to use this command. One of the 3 command should download the requirements of project.

None of them work

**Comment by poyrazinan** [comment]
Run mvn dependency:copy-dependencies, to download all your dependencies and save them in the target/dependency folder.

**Comment by Justman100** [comment]
> Run mvn dependency:copy-dependencies, to download all your dependencies and save them in the target/dependency folder.

Also not

**Comment by poyrazinan** [comment]
Then please use intellij idea to compile

**Comment by Justman100** [comment]
> Then please use intellij idea to compile

Habe es in einer IDE versucht! nun kommt ein anderer Fehler:

> Could not resolve dependencies for project xyz.geik.farmer:Farmer:jar:v6-b100: Failed to collect dependencies at com.github.Geik-xyz:GLib:jar:cd0ced12e5 -> eu.okaeri:okaeri-configs-yaml-bukkit:jar:4.0.4: Failed to read artifact descriptor for eu.okaeri:okaeri-configs-yaml-bukkit:jar:4.0.4: The following artifacts could not be resolved: eu.okaeri:okaeri-configs-yaml-bukkit:pom:4.0.4 (absent): Could not transfer artifact eu.okaeri:okaeri-configs-yaml-bukkit:pom:4.0.4 from/to okaeri-repo (https://storehouse.okaeri.eu/repository/maven-public/)

**Comment by Justman100** [comment]
> Then please use intellij idea to compile

I tried it in an IDE! now I get another error:

> Could not resolve dependencies for project xyz.geik.farmer:Farmer:jar:v6-b100: Failed to collect dependencies at com.github.Geik-xyz:GLib:jar:cd0ced12e5 -> eu.okaeri:okaeri-configs-yaml-bukkit:jar:4.0.4: Failed to read artifact descriptor for eu.okaeri:okaeri-configs-yaml-bukkit:jar:4.0.4: The following artifacts could not be resolved: eu.okaeri:okaeri-configs-yaml-bukkit:pom:4.0.4 (absent): Could not transfer artifact eu.okaeri:okaeri-configs-yaml-bukkit:pom:4.0.4 from/to okaeri-repo (https://storehouse.okaeri.eu/repository/maven-public/)

**Comment by Justman100** [comment]
> Then please use intellij idea to compile

I tried it in an IDE! Now I get another error:

> Could not resolve dependencies for project xyz.geik.farmer:Farmer:jar:v6-b100: Failed to collect dependencies at com.github.Geik-xyz:GLib:jar:cd0ced12e5 -> eu.okaeri:okaeri-configs-yaml-bukkit:jar:4.0.4: Failed to read artifact descriptor for eu.okaeri:okaeri-configs-yaml-bukkit:jar:4.0.4: The following artifacts could not be resolved: eu.okaeri:okaeri-configs-yaml-bukkit:pom:4.0.4 (absent): Could not transfer artifact eu.okaeri:okaeri-configs-yaml-bukkit:pom:4.0.4 from/to okaeri-repo (https://storehouse.okaeri.eu/repository/maven-public/)

**Comment by Justman100** [comment]
@poyrazinan

**Comment by Justman100** [comment]
@poyrazinan

WHY CLOSED?
