### ISSUE TITLE
[BUG] SuperiorSkyblock2 Çiftçi Üyeleri Sorunu

### ISSUE THREAD

**Issue by Smallturtless** [Geik-xyz/Farmer-v6#43]
Çiftçiye kayıtlı oyuncular yardımcı olsa dahi herhangi bir işlem yapamıyor.
https://github.com/Geik-xyz/Farmer-v6/assets/76789415/578c82bc-e5a3-49d0-b1a1-685490233b1b

**Comment by poyrazinan** [comment]
Yardımcı rolü CO-OP'dan gelmektedir. Üye'nin alt yetkisidir sadece çiftçi envanterini görüntüleme yetkisine sahiptir.

Sonraki güncelleme milestone'una default rank ve yardımcı rolünün adını değiştirme ekleyeceğim. Bu konu anlaşılmıyor çoğu kişi tarafından
