### ISSUE TITLE
[BUG] Farmer doesn't work in Towny.

### ISSUE THREAD

**Issue by LeBlach** [Geik-xyz/Farmer-v6#46]
Farmer V6 is not working properly with the latest version of Towny. You cannot buy a farmer in any plot, and even if a player has not bought a farmer in his plot, the crops are corrupted as if there was a farmer there. 

PlotClaim method has been changed, so I think that's why it doesn't work.

Server Version: 1.17.1
Farmer ver: v6

**Comment by poyrazinan** [comment]
Checked towny and couldn't find issue.
