### ISSUE TITLE
[BUG] Voucher Module Bug

### ISSUE THREAD

**Issue by pelicano0** [Geik-xyz/Farmer-v6#85]
**Describe the bug**
Eggs higher than level 1 in the voucher addon cannot exceed the level 1 limit when placed.

**To Reproduce**
Install the Farmer V6 plugin, enable the voucher addon, and give yourself a Farmer egg higher than level 1. Then, place it in any of your claims, and you will see that it doesn't exceed the level 1 limit.

**Expected behavior**
The egg in the Farmer's voucher plugin needs to provide the correct limit.

**Screenshots**
No Screenshots needed

**Logging**
No logging needed

**Give me which version of Farmer do you use**
Farmer-b106

**Write your server version**
PurpurMC 1.20.4

**Additional context**
There is no other context.

**Comment by poyrazinan** [comment]
Couldn't find the issue. It works perfect on b107

**Comment by pelicano0** [comment]
![Ekran görüntüsü 2024-08-17 231439](https://github.com/user-attachments/assets/7458f0d8-867a-4efa-b67e-259bc64c7097)
The issue persists even after building from the source code.
