### ISSUE TITLE
[BUG] Voucher Module Level Bug

### ISSUE THREAD

**Issue by pelicano0** [Geik-xyz/Farmer-v6#87]
**Describe the bug**
Eggs higher than level 1 in the voucher addon cannot exceed the level 1 limit when placed.

**To Reproduce**
Install the Farmer V6 plugin, enable the voucher addon, and give yourself a Farmer egg higher than level 1. Then, place it in any of your claims, and you will see that it doesn't exceed the level 1 limit.

**Expected behavior**
The egg in the Farmer's voucher plugin needs to provide the correct limit.

**Screenshots**
![image](https://github.com/user-attachments/assets/7752d6cf-0e7c-401a-b974-eef99306c638)

**Logging**
No logging needed

**Give me which version of Farmer do you use**
Farmer-b107 (Builded from the source code.)

**Write your server version**
PurpurMC 1.20.4

**Additional context**
There is no other context.

**Comment by poyrazinan** [comment]
couldn't find the issue
